sequenceDiagram
  autonumber
  participant User as Người dùng
  participant TVLApp as Ứng dụng TVL
  participant PayPayApp as App PayPay
  participant PayPayLogin as PayPay Login
  participant Consent as Màn hình chấp thuận
  participant TVLBE as TVL Backend

  Note over User,TVLApp: Bắt đầu luồng xử lý
  
  User->>TVLApp: 1. Ấn nút "Đổi điểm PayPay"
  alt Có cài App PayPay
    TVLApp->>PayPayApp: 2. Mở App PayPay
    

    opt Môi trường phát triển
      PayPayApp->>PayPayApp: Bật Developer Mode (ấn logo 7 lần)

    end
    PayPayApp->>PayPayLogin: Kiểm tra Login PayPay

    opt Chưa Login PayPay
      PayPayLogin-->>PayPayApp: Hiển thị màn hình Login PayPay
      User->>PayPayApp: Gửi thông tin đăng nhập Phone/Password
      PayPayApp->>PayPayLogin: Gửi thông tin đăng nhập Phone/Password
      PayPayLogin-->>Consent: Hiển thị màn hình chấp thuận 
      User->>Consent: Chập nhận liên kết
      
    end
  
  else Không có App PayPay
    TVLApp->>TVLApp: 2. Điều hướng đến PayPay
    opt Môi trường phát triển
      TVLApp->>TVLApp: 2. Điều hướng đến PayPay (Sandbox)
    end
    TVLApp->>PayPayLogin: Kiểm tra Login PayPay

    opt Chưa Login PayPay
      PayPayLogin-->>TVLApp: Điều hướng đến trang Login PayPay
      User->>TVLApp: Gửi thông tin đăng nhập Phone/Password
      TVLApp->>PayPayLogin: Gửi thông tin đăng nhập Phone/Password
      PayPayLogin-->>Consent: Hiển thị màn hình chấp thuận 
      User->>Consent: Chấp nhận liên kết
    end
    
  end
  Consent-->>TVLBE: Response API liên kết thành công kèm Authorization Code
  opt iOS
  TVLBE-->>TVLApp: Điều hướng về TVL (/mypage) kèm theo Token thông qua Deeplink:Onelink
  end
  opt Android
  TVLBE-->>TVLApp: Điều hướng về TVL (/mypage) kèm theo Token thông qua URL Scheme
  end
  
  TVLBE->>PayPayLogin: 8. Gọi API lấy Access Token
  PayPayLogin-->>TVLBE: 9. Trả về Access Token
  TVLBE->>TVLBE: 10. Lưu token & thông tin vào bảng Session
  TVLApp-->>User: Kết thúc liên kết


  Note over User,TVLBE: Kết thúc luồng xử lý đăng nhập & liên kết